import { z } from "zod"

// Define the schema for form field options
export const formFieldOptionSchema = z.object({
  label: z.string(),
  value: z.string(),
})

// Define the base schema for a form field
export const baseFormFieldSchema = z.object({
  name: z.string(),
  label: z.string(),
  placeholder: z.string().optional(),
  required: z.boolean().default(false),
  description: z.string().optional(),
})

// Define schemas for different input types
export const textInputSchema = baseFormFieldSchema.extend({
  type: z.literal("text"),
  inputType: z.enum(["text", "email", "password", "number", "tel", "link"]).default("text"),
})

export const textareaInputSchema = baseFormFieldSchema.extend({
  type: z.literal("textarea"),
})

export const checkboxInputSchema = baseFormFieldSchema.extend({
  type: z.literal("checkbox"),
  options: z.array(formFieldOptionSchema).optional(), // For group checkboxes
})

export const radioInputSchema = baseFormFieldSchema.extend({
  type: z.literal("radio"),
  options: z.array(formFieldOptionSchema),
})

export const selectInputSchema = baseFormFieldSchema.extend({
  type: z.literal("select"),
  options: z.array(formFieldOptionSchema),
})

export const multiSelectInputSchema = baseFormFieldSchema.extend({
  type: z.literal("multiselect"),
  options: z.array(formFieldOptionSchema),
})

export const dateInputSchema = baseFormFieldSchema.extend({
  type: z.literal("date"),
})

export const signatureInputSchema = baseFormFieldSchema.extend({
  type: z.literal("signature"),
})

// Union type for all possible form field schemas
export const formFieldSchema = z.discriminatedUnion("type", [
  textInputSchema,
  textareaInputSchema,
  checkboxInputSchema,
  radioInputSchema,
  selectInputSchema,
  multiSelectInputSchema,
  dateInputSchema,
  signatureInputSchema,
])

export type FormField = z.infer<typeof formFieldSchema>
export type FormFieldOption = z.infer<typeof formFieldOptionSchema>

// Define the comprehensive form fields for the hotel membership based on PDF
export const formFields: FormField[] = [
  // MEMBER DETAILS SECTION
  {
    name: "memberType",
    label: "Member Type",
    type: "radio",
    required: true,
    options: [
      { label: "Individual", value: "individual" },
      { label: "Firm", value: "firm" },
    ],
    description: "Select your membership type",
  },
  {
    name: "salutation",
    label: "Salutation",
    type: "select",
    required: true,
    options: [
      { label: "Mr.", value: "mr" },
      { label: "Ms.", value: "ms" },
      { label: "Mrs.", value: "mrs" },
    ],
    placeholder: "Select salutation",
  },
  {
    name: "firstName",
    label: "First Name",
    type: "text",
    inputType: "text",
    placeholder: "Enter your first name",
    required: true,
  },
  {
    name: "middleName",
    label: "Middle Name",
    type: "text",
    inputType: "text",
    placeholder: "Enter your middle name",
    required: false,
  },
  {
    name: "lastName",
    label: "Last Name",
    type: "text",
    inputType: "text",
    placeholder: "Enter your last name",
    required: true,
  },
  {
    name: "dateOfBirth",
    label: "Date of Birth",
    type: "date",
    required: true,
    description: "Please select your date of birth",
  },
  {
    name: "ageRange",
    label: "Age Range",
    type: "radio",
    required: true,
    options: [
      { label: "28-35", value: "28-35" },
      { label: "35-45", value: "35-45" },
      { label: "45-60", value: "45-60" },
      { label: "60 & Above", value: "60+" },
    ],
  },
  {
    name: "occupation",
    label: "Occupation",
    type: "radio",
    required: true,
    options: [
      { label: "Salaried", value: "salaried" },
      { label: "Business", value: "business" },
      { label: "Self Employed", value: "selfEmployed" },
      { label: "Others", value: "others" },
    ],
  },
  {
    name: "profession",
    label: "Profession",
    type: "text",
    inputType: "text",
    placeholder: "Enter your profession",
    required: true,
  },
  {
    name: "firmName",
    label: "Firm Name",
    type: "text",
    inputType: "text",
    placeholder: "Enter your firm name",
    required: false,
  },
  {
    name: "designation",
    label: "Designation",
    type: "text",
    inputType: "text",
    placeholder: "Enter your designation",
    required: false,
  },
  {
    name: "facebookId",
    label: "Facebook ID",
    type: "text",
    inputType: "text",
    placeholder: "Enter your Facebook ID",
    required: false,
  },
  {
    name: "twitterId",
    label: "Twitter ID",
    type: "text",
    inputType: "text",
    placeholder: "Enter your Twitter ID",
    required: false,
  },
  {
    name: "hasOwnCar",
    label: "Which car do you drive?",
    type: "text",
    inputType: "text",
    placeholder: "Enter your car details",
    required: false,
  },
  {
    name: "annualIncome",
    label: "Annual Income Category",
    type: "radio",
    required: true,
    options: [
      { label: "8-12 Lacs", value: "8-12lacs" },
      { label: "12-18 Lacs", value: "12-18lacs" },
      { label: "18-22 Lacs", value: "18-22lacs" },
      { label: "22 Lacs & Above", value: "22lacs+" },
    ],
  },
  {
    name: "foodPreference",
    label: "Food Preference",
    type: "radio",
    required: true,
    options: [
      { label: "Veg", value: "veg" },
      { label: "Non-Veg", value: "nonVeg" },
    ],
  },
  {
    name: "cuisinePreference",
    label: "Cuisine Preference",
    type: "multiselect",
    required: false,
    options: [
      { label: "Indian", value: "indian" },
      { label: "Chinese", value: "chinese" },
      { label: "Continental", value: "continental" },
    ],
    placeholder: "Select cuisine preferences",
  },
  {
    name: "holidayDestination",
    label: "Where did you holiday last?",
    type: "radio",
    required: false,
    options: [
      { label: "India", value: "india" },
      { label: "Abroad", value: "abroad" },
    ],
  },

  // CO-APPLICANT DETAILS SECTION
  {
    name: "coApplicantSalutation",
    label: "Co-Applicant Salutation",
    type: "select",
    required: false,
    options: [
      { label: "Mr.", value: "mr" },
      { label: "Ms.", value: "ms" },
      { label: "Mrs.", value: "mrs" },
    ],
    placeholder: "Select salutation",
  },
  {
    name: "coApplicantFirstName",
    label: "Co-Applicant First Name",
    type: "text",
    inputType: "text",
    placeholder: "Enter co-applicant's first name",
    required: false,
  },
  {
    name: "coApplicantMiddleName",
    label: "Co-Applicant Middle Name",
    type: "text",
    inputType: "text",
    placeholder: "Enter co-applicant's middle name",
    required: false,
  },
  {
    name: "coApplicantLastName",
    label: "Co-Applicant Last Name",
    type: "text",
    inputType: "text",
    placeholder: "Enter co-applicant's last name",
    required: false,
  },
  {
    name: "coApplicantRelationship",
    label: "Relationship with main applicant",
    type: "text",
    inputType: "text",
    placeholder: "e.g., Spouse, Partner, etc.",
    required: false,
  },
  {
    name: "coApplicantDateOfBirth",
    label: "Co-Applicant Date of Birth",
    type: "date",
    required: false,
  },
  {
    name: "coApplicantStdCode",
    label: "Co-Applicant STD Code",
    type: "text",
    inputType: "text",
    placeholder: "STD Code",
    required: false,
  },
  {
    name: "coApplicantPhone",
    label: "Co-Applicant Phone",
    type: "text",
    inputType: "tel",
    placeholder: "Phone number",
    required: false,
  },
  {
    name: "coApplicantFax",
    label: "Co-Applicant Fax",
    type: "text",
    inputType: "text",
    placeholder: "Fax number",
    required: false,
  },
  {
    name: "coApplicantMobile",
    label: "Co-Applicant Mobile",
    type: "text",
    inputType: "tel",
    placeholder: "Mobile number",
    required: false,
  },
  {
    name: "coApplicantEmail",
    label: "Co-Applicant Email",
    type: "text",
    inputType: "email",
    placeholder: "Email address",
    required: false,
  },

  // SPOUSE & FAMILY DETAILS SECTION
  {
    name: "spouseSalutation",
    label: "Spouse Salutation",
    type: "select",
    required: false,
    options: [
      { label: "Mr.", value: "mr" },
      { label: "Mrs.", value: "mrs" },
    ],
    placeholder: "Select salutation",
  },
  {
    name: "spouseName",
    label: "Spouse Name",
    type: "text",
    inputType: "text",
    placeholder: "Enter spouse's name",
    required: false,
  },
  {
    name: "spouseDateOfBirth",
    label: "Spouse Date of Birth",
    type: "date",
    required: false,
  },
  {
    name: "weddingAnniversary",
    label: "Wedding Anniversary Date",
    type: "date",
    required: false,
  },
  {
    name: "numberOfChildren",
    label: "Number of Children",
    type: "text",
    inputType: "number",
    placeholder: "Enter number of children",
    required: false,
  },
  {
    name: "child1Name",
    label: "Child 1 Name",
    type: "text",
    inputType: "text",
    placeholder: "Enter child's name",
    required: false,
  },
  {
    name: "child1Gender",
    label: "Child 1 Gender",
    type: "radio",
    required: false,
    options: [
      { label: "Male", value: "male" },
      { label: "Female", value: "female" },
    ],
  },
  {
    name: "child1DateOfBirth",
    label: "Child 1 Date of Birth",
    type: "date",
    required: false,
  },
  {
    name: "child2Name",
    label: "Child 2 Name",
    type: "text",
    inputType: "text",
    placeholder: "Enter child's name",
    required: false,
  },
  {
    name: "child2Gender",
    label: "Child 2 Gender",
    type: "radio",
    required: false,
    options: [
      { label: "Male", value: "male" },
      { label: "Female", value: "female" },
    ],
  },
  {
    name: "child2DateOfBirth",
    label: "Child 2 Date of Birth",
    type: "date",
    required: false,
  },
  {
    name: "child3Name",
    label: "Child 3 Name",
    type: "text",
    inputType: "text",
    placeholder: "Enter child's name",
    required: false,
  },
  {
    name: "child3Gender",
    label: "Child 3 Gender",
    type: "radio",
    required: false,
    options: [
      { label: "Male", value: "male" },
      { label: "Female", value: "female" },
    ],
  },
  {
    name: "child3DateOfBirth",
    label: "Child 3 Date of Birth",
    type: "date",
    required: false,
  },
  {
    name: "spouseMobile",
    label: "Spouse Mobile",
    type: "text",
    inputType: "tel",
    placeholder: "Mobile number",
    required: false,
  },
  {
    name: "spouseEmail",
    label: "Spouse Email",
    type: "text",
    inputType: "email",
    placeholder: "Email address",
    required: false,
  },

  // ADDRESS & CONTACT DETAILS SECTION
  {
    name: "premisesName",
    label: "Name of Premises/Building",
    type: "text",
    inputType: "text",
    placeholder: "Enter building/premises name",
    required: true,
  },
  {
    name: "roadStreetLane",
    label: "Road/Street/Lane",
    type: "text",
    inputType: "text",
    placeholder: "Enter road/street/lane",
    required: true,
  },
  {
    name: "areaLocality",
    label: "Area/Locality",
    type: "text",
    inputType: "text",
    placeholder: "Enter area/locality",
    required: true,
  },
  {
    name: "landmark",
    label: "Landmark",
    type: "text",
    inputType: "text",
    placeholder: "Enter landmark",
    required: false,
  },
  {
    name: "city",
    label: "City",
    type: "text",
    inputType: "text",
    placeholder: "Enter city",
    required: true,
  },
  {
    name: "state",
    label: "State",
    type: "text",
    inputType: "text",
    placeholder: "Enter state",
    required: true,
  },
  {
    name: "country",
    label: "Country",
    type: "text",
    inputType: "text",
    placeholder: "Enter country",
    required: true,
  },
  {
    name: "postalCode",
    label: "Postal Code (PIN)",
    type: "text",
    inputType: "text",
    placeholder: "Enter postal code",
    required: true,
  },
  {
    name: "contactStdCode",
    label: "STD Code",
    type: "text",
    inputType: "text",
    placeholder: "STD Code",
    required: false,
  },
  {
    name: "contactPhone",
    label: "Phone",
    type: "text",
    inputType: "tel",
    placeholder: "Phone number",
    required: false,
  },
  {
    name: "contactFax",
    label: "Fax",
    type: "text",
    inputType: "text",
    placeholder: "Fax number",
    required: false,
  },
  {
    name: "contactMobile",
    label: "Mobile",
    type: "text",
    inputType: "tel",
    placeholder: "Mobile number",
    required: true,
  },
  {
    name: "contactEmail",
    label: "Email",
    type: "text",
    inputType: "email",
    placeholder: "Email address",
    required: true,
  },

  // COMMUNICATION PREFERENCES SECTION
  {
    name: "preferredContactMethod",
    label: "Preferred Contact Method",
    type: "multiselect",
    required: true,
    options: [
      { label: "Mobile", value: "mobile" },
      { label: "Alternate Mobile No.", value: "alternateMobile" },
      { label: "Landline", value: "landline" },
      { label: "Spouse Mobile", value: "spouseMobile" },
      { label: "Co-Applicant Mobile No.", value: "coApplicantMobile" },
    ],
    placeholder: "Select preferred contact methods",
  },
  {
    name: "mailingAddress",
    label: "Mailing Address",
    type: "radio",
    required: true,
    options: [
      { label: "Residence", value: "residence" },
      { label: "Office", value: "office" },
      { label: "Contact No.", value: "contactNo" },
    ],
  },
  {
    name: "communicationMode",
    label: "Communication Mode",
    type: "multiselect",
    required: true,
    options: [
      { label: "Phone", value: "phone" },
      { label: "Email", value: "email" },
      { label: "Letter", value: "letter" },
    ],
    placeholder: "Select communication modes",
  },

  // PRODUCT DETAILS SECTION
  {
    name: "membershipCategory",
    label: "Membership Category",
    type: "radio",
    required: true,
    options: [
      { label: "Bronze", value: "bronze" },
      { label: "Silver", value: "silver" },
      { label: "Gold", value: "gold" },
      { label: "Platinum", value: "platinum" },
      { label: "Diamond", value: "diamond" },
    ],
  },
  {
    name: "membershipYears",
    label: "Number of Years",
    type: "text",
    inputType: "number",
    placeholder: "Enter number of years",
    required: true,
  },

  // PAYMENT DETAILS SECTION
  {
    name: "membershipPrice",
    label: "Membership Price (INR)",
    type: "text",
    inputType: "number",
    placeholder: "Enter membership price",
    required: true,
  },
  {
    name: "downPaymentAmount",
    label: "Down Payment Amount (INR)",
    type: "text",
    inputType: "number",
    placeholder: "Enter down payment amount",
    required: true,
  },
  {
    name: "downPaymentOption",
    label: "Down Payment Option",
    type: "radio",
    required: true,
    options: [
      { label: "Full Payment", value: "fullPayment" },
      { label: "30 DP", value: "30dp" },
      { label: "50 DP", value: "50dp" },
    ],
  },
  {
    name: "paymentMode",
    label: "Mode of Payment",
    type: "radio",
    required: true,
    options: [
      { label: "Demand Draft", value: "demandDraft" },
      { label: "Cheque", value: "cheque" },
      { label: "Credit Card", value: "creditCard" },
      { label: "Debit Card", value: "debitCard" },
      { label: "Cash", value: "cash" },
    ],
  },
  {
    name: "cashPaymentDate",
    label: "Cash Payment Date",
    type: "date",
    required: false,
  },
  {
    name: "cashPaymentAmount",
    label: "Cash Payment Amount",
    type: "text",
    inputType: "number",
    placeholder: "Enter cash amount",
    required: false,
  },
  {
    name: "cashReceiptNo",
    label: "Cash Receipt No.",
    type: "text",
    inputType: "text",
    placeholder: "Enter receipt number",
    required: false,
  },
  {
    name: "ddBankName",
    label: "Bank Name & Branch (DD/Cheque)",
    type: "text",
    inputType: "text",
    placeholder: "Enter bank name and branch",
    required: false,
  },
  {
    name: "ddInsuranceNo",
    label: "Insurance No. (DD/Cheque)",
    type: "text",
    inputType: "text",
    placeholder: "Enter insurance number",
    required: false,
  },
  {
    name: "ddDate",
    label: "DD/Cheque Date",
    type: "date",
    required: false,
  },
  {
    name: "creditCardNo",
    label: "Credit/Debit Card No.",
    type: "text",
    inputType: "text",
    placeholder: "Enter card number",
    required: false,
  },
  {
    name: "creditCardExpiry",
    label: "Credit/Debit Card Expiry Date",
    type: "date",
    required: false,
  },
  {
    name: "creditCardAuthNo",
    label: "Authorization No.",
    type: "text",
    inputType: "text",
    placeholder: "Enter authorization number",
    required: false,
  },
  {
    name: "creditCardType",
    label: "Credit Card Type",
    type: "multiselect",
    required: false,
    options: [
      { label: "VISA", value: "visa" },
      { label: "MASTER", value: "master" },
      { label: "AMEX", value: "amex" },
      { label: "DINERS", value: "diners" },
      { label: "Others", value: "others" },
    ],
    placeholder: "Select card types",
  },
  {
    name: "creditCardCategory",
    label: "Credit Card Category",
    type: "multiselect",
    required: false,
    options: [
      { label: "Platinum", value: "platinum" },
      { label: "Gold", value: "gold" },
      { label: "Silver", value: "silver" },
      { label: "Titanium", value: "titanium" },
      { label: "Others", value: "others" },
    ],
    placeholder: "Select card categories",
  },
  {
    name: "issuingBankName",
    label: "Issuing Bank Name",
    type: "text",
    inputType: "text",
    placeholder: "Enter issuing bank name",
    required: false,
  },

  // EMI PLAN SECTION
  {
    name: "emiOptedPercentage",
    label: "EMI Opted Percentage",
    type: "radio",
    required: false,
    options: [
      { label: "6%", value: "6" },
      { label: "12%", value: "12" },
    ],
  },
  {
    name: "emiPaymentMode",
    label: "EMI Payment Mode",
    type: "radio",
    required: false,
    options: [
      { label: "Cheque", value: "cheque" },
      { label: "Credit Card", value: "creditCard" },
      { label: "ECS", value: "ecs" },
    ],
  },
  {
    name: "emiThirdPartyPayment",
    label: "Third Party Payment",
    type: "checkbox",
    required: false,
  },
  {
    name: "emiBankName",
    label: "EMI Bank Name",
    type: "text",
    inputType: "text",
    placeholder: "Enter bank name",
    required: false,
  },
  {
    name: "emiInstrumentNo",
    label: "EMI Instrument No.",
    type: "text",
    inputType: "text",
    placeholder: "Enter instrument number",
    required: false,
  },
  {
    name: "emiDate",
    label: "EMI Date",
    type: "date",
    required: false,
  },
  {
    name: "emiCreditCardNo",
    label: "EMI Credit Card No.",
    type: "text",
    inputType: "text",
    placeholder: "Enter credit card number",
    required: false,
  },
  {
    name: "emiCreditCardExpiry",
    label: "EMI Credit Card Expiry",
    type: "date",
    required: false,
  },
  {
    name: "emiCreditCardAuthNo",
    label: "EMI Authorization No.",
    type: "text",
    inputType: "text",
    placeholder: "Enter authorization number",
    required: false,
  },
  {
    name: "emiCreditCardType",
    label: "EMI Credit Card Type",
    type: "multiselect",
    required: false,
    options: [
      { label: "VISA", value: "visa" },
      { label: "MASTER", value: "master" },
      { label: "AMEX", value: "amex" },
      { label: "Diners", value: "diners" },
      { label: "Others", value: "others" },
    ],
    placeholder: "Select card types",
  },
  {
    name: "ecsBank",
    label: "ECS Bank Name",
    type: "text",
    inputType: "text",
    placeholder: "Enter bank name",
    required: false,
  },
  {
    name: "ecsDate",
    label: "ECS Date",
    type: "date",
    required: false,
  },
  {
    name: "ecsMicrNo",
    label: "ECS MICR No.",
    type: "text",
    inputType: "text",
    placeholder: "Enter MICR number",
    required: false,
  },
  {
    name: "ecsSampleInstrumentNo",
    label: "ECS Sample Instrument No.",
    type: "text",
    inputType: "text",
    placeholder: "Enter sample instrument number",
    required: false,
  },

  // KYC DOCUMENTS SECTION
  {
    name: "kycDocumentType",
    label: "KYC Document Type (Individual)",
    type: "multiselect",
    required: true,
    options: [
      { label: "Ration Card", value: "rationCard" },
      { label: "Voter ID", value: "voterId" },
      { label: "Pan Card", value: "panCard" },
      { label: "Passport", value: "passport" },
      { label: "Driving License", value: "drivingLicense" },
    ],
    placeholder: "Select document types",
  },
  {
    name: "coApplicantKycDocumentType",
    label: "KYC Document Type (Co-applicant)",
    type: "multiselect",
    required: false,
    options: [
      { label: "Ration Card", value: "rationCard" },
      { label: "Voter ID", value: "voterId" },
      { label: "Pan Card", value: "panCard" },
      { label: "Passport", value: "passport" },
      { label: "Driving License", value: "drivingLicense" },
    ],
    placeholder: "Select document types",
  },
  {
    name: "executiveName",
    label: "Name of Coastal Grand Holidays & Resorts Executive",
    type: "text",
    inputType: "text",
    placeholder: "Enter executive name",
    required: false,
  },
  {
    name: "executiveCmeId",
    label: "CME ID",
    type: "text",
    inputType: "text",
    placeholder: "Enter CME ID",
    required: false,
  },
  {
    name: "executiveDate",
    label: "Executive Date",
    type: "date",
    required: false,
  },

  // SIGNATURES SECTION
  {
    name: "memberSignature",
    label: "Signature of the Member",
    type: "signature",
    required: true,
    description: "Please provide your digital signature",
  },
  {
    name: "coApplicantSignature",
    label: "Signature of the Co-applicant",
    type: "signature",
    required: false,
    description: "Co-applicant's digital signature (if applicable)",
  },
]
